- name: Log selection
  hosts: "all"
  tasks:
    - name: Create a directory if it does not exist
      file:
        path: /root/logs_temp
        state: directory
        mode: '0755'
    - name: Log archiving
      archive:
        path: "{{ item }}"
        dest: /root/logs_temp/logs-{{inventory_hostname_short}}-{{ ansible_date_time.date }}.tar.gz
        format: gz
        force_archive: true
      loop: 
        - /opt/qligent/vision/Logs/