- hosts: "all"
  archive:
  - name: Log archiving 
    archive:
      path: {{ item }}
      dest: /root/logs_temp/logs-{{inventory_hostname_short}}-{{date}}.tar.bz2
      format: gz
      force_archive: true
  ignore_errors: True
  loop: "{{ /opt/qligent/vision/Logs/ }}"