- name: Log selection
  hosts: "all"
  tasks:
    - name: Log archiving
      archive:
        path: "{{ item }}"
        dest: /root/logs_temp/logs-"{{inventory_hostname_short}}"-"{{ ansible_date_time.date }}".tar.gz
        format: gz
        force_archive: true
      loop: 
        - /opt/qligent/vision/Logs/