- name: Syncronize logs
  hosts: "all"
  tasks:
    - name: Copy logs
      fetch:
        src: /tmp/logs_temp/logs*
        dest: /home/semaphore/
        # delegate_to: localhost
        # owner: semaphore
        # group: semaphore
        # mode: '0644'