- name: Syncronize logs
  hosts: "all"
  tasks:
    - name: Copy logs
      synchronize:
        dest: /home/semaphore/
        src: /tmp/logs_temp/
        delegate_to: localhost
        # owner: semaphore
        # group: semaphore
        # mode: '0644'