- name: Syncronize logs
  hosts: "all"
  tasks:
    - name: Copy logs
      fetch:
        src: /tmp/logs_temp/log.tar.gz
        dest: /home/semaphore/log-{{inventory_hostname_short}}-{{ ansible_date_time.date }}.tar.gz
        # delegate_to: localhost
        # owner: semaphore
        # group: semaphore
        # mode: '0644'