- name: Syncronize logs
  hosts: "all"
  tasks:
    - name: Copy logs
      fetch:
        dest: /home/semaphore/
        src: /tmp/logs_temp/
        remote_src: yes 
        # owner: semaphore
        # group: semaphore
        # mode: '0644'