- name: Syncronize logs
  hosts: "all"
  tasks:
    - name: Copy logs
      copy:
        dest: /home/semaphore/
        src: /root/logs_temp/
        owner: semaphore
        group: semaphore
        mode: '0644'