- name: Syncronize logs
  hosts: "all"
  tasks:
    - name: Copy logs
      fetch:
        src: "{{ item }}"
        dest: /home/semaphore/
      with_fileglob: 
        - "/tmp/logs_temp/logs*"
        # delegate_to: localhost
        # owner: semaphore
        # group: semaphore
        # mode: '0644'